#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["Valuation.Console/Valuation.Console.csproj", "Valuation.Console/"]
COPY ["Valuation.WorldTradingData.Service/Valuation.WorldTradingData.Service.csproj", "Valuation.WorldTradingData.Service/"]
COPY ["Valuation.Service/Valuation.Service.csproj", "Valuation.Service/"]
COPY ["Valuation.Common/Valuation.Common.csproj", "Valuation.Common/"]
COPY ["Valuation.Domain/Valuation.Domain.csproj", "Valuation.Domain/"]
COPY ["Valuation.WorldTradingData.Repository/Valuation.Repository.csproj", "Valuation.WorldTradingData.Repository/"]
COPY ["Valuation.Infrastructure/Valuation.Infrastructure.csproj", "Valuation.Infrastructure/"]
RUN dotnet restore "Valuation.Console/Valuation.Console.csproj"
COPY . .
WORKDIR "/src/Valuation.Console"
RUN dotnet build "Valuation.Console.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Valuation.Console.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Valuation.Console.dll"]